module.exports = {
    title_max_char: 20,
    desc_max_blocks: 30,
    pdf_max_size: 1000000,
    pdf_format: 'application/pdf',
    pdf_max_width: 1000,
    pdf_max_height: 1000,
    pdf_min_width: 200,
    pdf_min_height: 200,
    desc_file_max_size: 10000000,
    desc_file_format: ['image/png', 'image/jpg', 'image/jpeg'],
    desc_file_max_width: 3000,
    desc_file_max_height: 3000,
    desc_file_min_width: 100,
    desc_file_min_height: 100,
    profile_max_size: 1000000,
    profile_formats: ['image/png', 'image/jpg', 'image/jpeg'],
    profile_max_width: 2000,
    profile_max_height: 2000,
    profile_min_width: 200,
    profile_min_height: 200,
    username_max_char: 10,
    password_max_char: 20,
    password_min_char: 5,
    email_max_char: 40,
    email_includes: "@",
    file_max_name: 20,
    comment_max_blocks: 10,
    file_contains: "https://res.cloudinary.com/dnu6yyl9d/image/upload/v1645538236/ctice",
    location_max_chars: 50,
    bio_max_blocks: 20,
    facebook_connection_includes: "facebook.com",
    twitter_connection_includes: "twitter.com",
    linkedin_connection_includes: "linkedin.com",
    gallery_length: 20,
    dates_length: 100,
    block_max_chars: 1000,
    banner_max_size: 1000000,
    notification_max_size: 1000000,
    declr_max_tags: 5,
    declr_min_tags: 1,
    tag_max_length: 20
}
